### ISSUE TITLE
Bug accessing the character page via URL

### ISSUE THREAD

**Issue by Yeldur** [verdie-g/crpg#1044]
**Describe the bug**
When trying to navigate straight to the character page via URL, you are instead presented with an error page, meaning you have to navigate from the homepage instead, which is tedious.

**To Reproduce**
1. Open URL with: https://c-rpg.eu/characters/**CharIDGOESHERE**/inventory
2. See error

**Expected behavior**
Should take you straight to your character page and let you view your inventory.

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.
![image](https://github.com/verdie-g/crpg/assets/113024735/2bc7497c-efbc-448d-93e7-c70692242654)

**Context**
 - OS: [e.g. Windows] Windows 10
 - Browser (in case of a bug on the website) [e.g. chrome, firefox] FireFox Ver 114.0.1 (up-to-date)

**Comment by or2e** [comment]
cache

**Comment by Yeldur** [comment]
PEBCAK -> closing
