### ISSUE TITLE
Add clans to leaderboard

### ISSUE THREAD

**Issue by or2e** [verdie-g/crpg#1086]
https://discord.com/channels/279063743839862805/1122239138834419772

**Comment by verdie-g** [comment]
I think that makes sense to add the clan to the public user view.

**Comment by or2e** [comment]
> I think that makes sense to add the clan to the public user view.

great idea!

**Comment by or2e** [comment]
link https://github.com/verdie-g/crpg/pull/1088

**Comment by or2e** [comment]
resolver: https://github.com/verdie-g/crpg/pull/1094
