### ISSUE TITLE
MMR is lost when switching characters to one with lower MMR

### ISSUE THREAD

**Issue by Yeldur** [verdie-g/crpg#1089]
**Describe the bug**
When playing on Character X with high MMR, users reported switching to lower MMR characters, after switching back, their MMR on their main character was lowered as a result - 2x reports of this from 2 separate regions so far (1x EU, 1x NA) 

**To Reproduce (UNTESTED - WILL NEED TO BE CHECKED)**
1) Have main Character set as active on high MMR 
2) Exit game, switch to secondary character on lower MMR
3) Play for 1 round (So that autobalancer can apply)
4) Switch back to main character
5) MMR should then change

**Expected behavior**
Unclear if this is expected behaviour, from my understanding each character should have its own distinct MMR, and the two should not overlap (???)

**Screenshots/Videos**
![image](https://github.com/verdie-g/crpg/assets/113024735/f24a6113-fd5c-4fc7-a6df-acc1448ac3d2)
&
https://discord.com/channels/279063743839862805/761283333840699392/1122375287594823760

**Context**
 - OS: [e.g. Windows]
 - Browser (in case of a bug on the website) [e.g. chrome, firefox]
 - Bannerlord version (in case of a bug in game) [e.g. e1.5.4] v1.1.5
 - cRPG version (in case of a bug in game) [e.g. 0.1.2] v69

**Comment by Yeldur** [comment]
For reference, I can validate that Alper Tunga was at least top 20 when I looked at leaderboards yesterday

**Comment by or2e** [comment]
resolved: https://github.com/verdie-g/crpg/pull/1091
