### ISSUE TITLE
[QoL] Personalised Inventory ordering

### ISSUE THREAD

**Issue by Rogerdin13** [verdie-g/crpg#1090]
I would like to persist my inventory sorting on the characterpage:
![grafik](https://github.com/verdie-g/crpg/assets/75375078/f10ec9a9-d981-45b4-9470-dca953c58d13)

When i set it to 'By type', go to my character overview/check equip of another cha and then go back to inventory tab it default s back to 'By rank', which is annoying to me.

Idea/Solution:
IMO best would be an approach where settings like these are somewhat persisted in the DB per user/player and after the login/auth step can be applied automatically.

So idea would be to save these settings when changed in the Backend an manage them in the Frontend.

If backend persistance is not an option just 'per session' persistance would be fine to me.

**Comment by verdie-g** [comment]
Let's slap a local localStorage entry on that problem @or2e ?

**Comment by or2e** [comment]
No problem
