### ISSUE TITLE
New item filter on website

### ISSUE THREAD

**Issue by or2e** [verdie-g/crpg#1102]
https://discord.com/channels/279063743839862805/1123657690644754565

**Comment by or2e** [comment]
@namidaka @verdie-g 

CRPG1 was missing thumbnails for recently added items ;)

What are your ideas?

**Comment by verdie-g** [comment]
Hmm you can use the `created_at` column though it will bumped whenever an item had a lot of changes. It might not be an issue. I can expose this through the API if it's not already the case.
