### ISSUE TITLE
Disallow setting your character for tournament after lvl 25

### ISSUE THREAD

**Issue by verdie-g** [verdie-g/crpg#1122]
Some people got fucked by doing that on their lvl 30 character.

**Comment by or2e** [comment]
https://github.com/verdie-g/crpg/blob/master/src/WebUI/src/services/characters-service.ts#L69C77-L69C77

 ~~character.level > tournamentLevel~~ => `character.level >= tournamentLevel` ?

**Comment by verdie-g** [comment]
That checks that they are under the tournament level but we should be safer and lower the check to 25.
