### ISSUE TITLE
Refreshing the auth token breaks the website

### ISSUE THREAD

**Issue by verdie-g** [verdie-g/crpg#1164]
The access token has a 1 hour lifetime. The refresh seems to break the website.
![image](https://github.com/verdie-g/crpg/assets/9092290/ae54a01d-a97c-4311-9432-626a5b423eb2)

**Comment by or2e** [comment]
Tried to reproduce by changing the token lifetime value, no luck so far. I'll keep looking
`options.SetAccessTokenLifetime(TimeSpan.FromMinutes(1));`

**Comment by verdie-g** [comment]
I get that error whenever I let my computer on for an hour.

**Comment by or2e** [comment]
ok, I'll try to reproduce it, maybe not only AccessTokenLifetime is responsible for it.
https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Server/OpenIddictServerOptions.cs#L187C22-L187C42
