### ISSUE TITLE
The welcome message is broken

### ISSUE THREAD

**Issue by or2e** [verdie-g/crpg#1192]
Apparently because of [this](https://github.com/verdie-g/crpg/pull/1180/files#diff-a29fe75652b5fbea817f5c86d710d79e03ae537f0425e9821310b377f8d660c7L89) edit, but it's unclear why.

https://cdn.discordapp.com/attachments/837422945911570462/1132166058929827952/image.png

**Comment by verdie-g** [comment]
Also I've noticed the team balance message is not pluralized correctly.
