### ISSUE TITLE
Disallow big shields on horses

### ISSUE THREAD

**Issue by verdie-g** [verdie-g/crpg#366]

**Comment by verdie-g** [comment]
Discord feedback https://discord.com/channels/279063743839862805/1092882043874062478

@or2e can you disable equipping item with class LargeShield if the character has a horse? This class is not used yet, we'll have to figure how to use it.

**Comment by or2e** [comment]
Yes, but all shields have class `LargeShield `

**Comment by verdie-g** [comment]
Oh ok, well we'll figure what to put in Small/Large

**Comment by namidaka** [comment]
@or2e @verdie-g  don't not mess up with shield class small/large . Small shield is unused and may be causing problems.
What about just editing spawning behaviour to not make a shield spawn if you're on horseback?

**Comment by verdie-g** [comment]
@Meowkov told me it was fine

**Comment by verdie-g** [comment]
Keeping open because we need to add the CantUseOnHorseBack on the shields.
