### ISSUE TITLE
Add dot net sdk local install on Ansible deployment script

### ISSUE THREAD

**Issue by namidaka** [verdie-g/crpg#878]
Can we put a task on ansible to install dot net sdk 7.0 locally (includes adding the official microsoft repo)  https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

**Comment by verdie-g** [comment]
I suppose that would make sense. Though it's super tricky to make this portable (between Linux distributions).

**Comment by or2e** [comment]
https://mcr.microsoft.com/v2/devcontainers/dotnet/tags/list

https://github.com/verdie-g/crpg/blob/master/.devcontainer/Dockerfile#L4 
~~7.0-bullseye~~ -> `7.0-jammy` ?

**Comment by verdie-g** [comment]
Yep that was I was thinking of. We could use a docker image containing node and .NET. Though between installing Docker and .NET + Node I'm not sure what's easier.

**Comment by verdie-g** [comment]
Won't do, portable installation is too much work for what it's worth.
