### ISSUE TITLE
Avoid printing 0 online players on error

### ISSUE THREAD

**Issue by verdie-g** [verdie-g/crpg#895]
Players rely a lot on the online counter before joining a server. This counter can return 0 when datadog has an issue, or the web API is down, or we the query failed for some connection error. We should print ? instead of 0.

**Comment by verdie-g** [comment]
@or2e I'll return null if the stats cannot be fetched. Could you handle that case 🙏

**Comment by or2e** [comment]
`We should print
instead of 0.`

Should we print an error message?

**Comment by verdie-g** [comment]
Fixed. We should print `?`
