### ISSUE TITLE
Not spawning after going to spec in battle and respeccing

### ISSUE THREAD

**Issue by namidaka** [verdie-g/crpg#909]
**Describe the bug**

**To Reproduce**
1.Go to a battle server
2.Click on spectator
3. Respec
4. select a team way before and of round
5. You do not spawn

**Expected behavior**
I'm expecting to spawn

**Comment by Rogerdin13** [comment]
for reference, i tried to narrow down the issue by experiencing it myself:
https://discord.com/channels/279063743839862805/1100196075899457607

**Comment by or2e** [comment]
Bug confirmed

**Comment by verdie-g** [comment]
I don't have access to Bannerlord but if you want to debug that the offending code is probably here: https://github.com/verdie-g/crpg/blob/e6eac874db1bd5d1a5973f5dcb38be93ef38468b/src/Module.Server/Common/CrpgTeamSelectComponent.cs#L78-L118

**Comment by jimbojammesi** [comment]
The spectator issue seems unrelated to respec. Recreate by:
1. Join spectator mode at any time after warmup round.
2. Can not get put on a team until the map ends on Battle and Conquest

The only time that a player can join spectator and then get put on a team is during the warm up round currently. What confuses me is that spectator mode used to function properly in Battle, but I can't find the direct time in which it stopped. My current guess based on earliest report is around the time of: https://github.com/verdie-g/crpg/commit/1e63045734a8fe38a3f4476e3cb4b12b9c561af7 but that commit did not touch the above HandleTeamChange(NetworkCommunicator peer, TeamChange message) function code.
