### ISSUE TITLE
No Valour in 1st round

### ISSUE THREAD

**Issue by or2e** [verdie-g/crpg#943]
https://discord.com/channels/279063743839862805/837422945911570462/1102343886485078167

https://github.com/verdie-g/crpg/commit/5b529335b012b4f2b2d98aec629dc790a888adf7

https://github.com/verdie-g/crpg/commit/f58ca163dddc5bfc335334e34cd0fa5f65d6110f

**Comment by verdie-g** [comment]
Just got valour of first round.
