### ISSUE TITLE
Upkeep/Gold/Exp on first round without spawning in

### ISSUE THREAD

**Issue by dylparl** [verdie-g/crpg#950]
**Describe the bug**
When you join a server you receive gold/upkeep/exp for the round even if you joined too late to spawn.

**To Reproduce**
1. Join the server when a round has already started
2. Wait until round ends
3. See gold/upkeep/exp in chat

**Expected behavior**
To only receive rewards/pay upkeep in rounds in which you have spawned in

**Screenshots/Videos**
I don't have any available, though I have personal testimony as well as a thread active on the discord w/ others reporting the same behavior 

**Context**
It's 100% happening in V64 but I believe this behavior has been around for several weeks/patches

**Comment by dylparl** [comment]
https://discord.com/channels/279063743839862805/1103796410794659880

Thread in question

**Comment by namidaka** [comment]
Can confirm , happened to me too
