### ISSUE TITLE
Bots fail to let you rejoin your team once spawned in your place

### ISSUE THREAD

**Issue by Yeldur** [verdie-g/crpg#954]
**Describe the bug**
Upon entering spectator mode during a round, a bot may spawn to fill your place, in doing so, you are now locked out of the game until the next map, because the bot will not let you re-claim your place.

**To Reproduce**
1) Be playing on a server that has bots spawn in place of humans
2) Switch to spectator temporarily
3) Switch back after being finished and try to join a team

**Expected behavior**
Should enable you to rejoin your team, but does not. The bot has now stolen your place and you are stuck in limbo permanently until the next map. Rejoining does not work, reloading your game does not work, switching off and on spectator does not work.

**Screenshots/Videos**
N/A

**Context**
 - cRPG version (in case of a bug in game) v64

**Comment by verdie-g** [comment]
It is unlikely related to bots but rather something around joining a team after being spectator like in https://github.com/verdie-g/crpg/issues/909.

**Comment by Yeldur** [comment]
Makes sense, my bad, I didn't spot that one - Closed with ref to #909
